<?php
/**
 * Plugin Name:       FireHawkCRM Tributes - Plausible Analytics Integration
 * Plugin URI:        https://github.com/weavedigitalstudio/fcrm-plausible-analytics
 * Description:       Adds Plausible Analytics tracking to single tribute pages generated by the FireHawk CRM Tributes plugin.
 * Version:           1.0.1
 * Author:            Weave Digital Studio
 * License:           GPL-3.0
 * GitHub Plugin URI: https://github.com/weavedigitalstudio/fcrm-plausible-analytics
 * Primary Branch:    main
 * Requires at least: 6.0
 * Requires PHP:      7.2
 */

/*
Changelog:
Version 1.0.1
- Added plugin updator

Version 1.0
- Initial release, adds Plausible Analytics tracking to dynamically generated tribute pages.
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Check if the Plausible Analytics plugin is active
if ( in_array( 'plausible-analytics/plausible-analytics.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {

    function load_plausible_on_tribute_pages() {
        // Check if we are on a tribute page by checking for specific query parameters or conditions
        if ( isset($_GET['id']) && isset($_GET['tid']) ) {
            // Assuming that if these query parameters are present, we are on a tribute page
            // Get the Plausible Analytics script URL
            $script_url = Plausible\Analytics\WP\Helpers::get_js_url( true );
            // Get the version (adapt this part based on the plugin's logic)
            $version = Plausible\Analytics\WP\Helpers::proxy_enabled() && file_exists( Plausible\Analytics\WP\Helpers::get_js_path() ) ? filemtime( Plausible\Analytics\WP\Helpers::get_js_path() ) : PLAUSIBLE_ANALYTICS_VERSION;
            
            // Enqueue the Plausible Analytics script
            wp_enqueue_script( 'plausible-analytics', $script_url, [], $version, apply_filters( 'plausible_load_js_in_footer', false ) );

            // Add the inline script for goal tracking (optional)
            wp_add_inline_script(
                'plausible-analytics',
                'window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }'
            );
        }
    }
    add_action( 'wp_enqueue_scripts', 'load_plausible_on_tribute_pages' );

} else {
    add_action( 'admin_notices', function() {
        echo '<div class="error"><p><strong>FireHawkCRM Tributes - Plausible Analytics Integration:</strong> The Plausible Analytics plugin is not active. Please activate the Plausible Analytics plugin to use this plugin.</p></div>';
    });
}
