<?php
/**
 * Plugin Name:       FireHawkCRM Tributes - Plausible Analytics Integration
 * Plugin URI:        https://github.com/weavedigitalstudio/fcrm-plausible-analytics
 * Description:       Adds Plausible Analytics tracking to single tribute pages generated by the FireHawk CRM Tributes plugin.
 * Version:           1.1.0
 * Author:            Weave Digital Studio
 * License:           GPL-3.0
 * Copyright (C) 2024 Weave Digital Studio Ltd
 * GitHub Plugin URI: https://github.com/weavedigitalstudio/fcrm-plausible-analytics
 * Primary Branch:    main
 * Requires at least: 6.0
 * Requires PHP:      7.2
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Define plugin constants
define( 'FCRM_PLAUSIBLE_VERSION', '1.1.0' );
define( 'FCRM_PLAUSIBLE_FILE', __FILE__ );

// Check if both required plugins are active
if ( in_array( 'plausible-analytics/plausible-analytics.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) 
    && in_array( 'fcrm-tributes/fcrm-tributes.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) 
) {
    /**
     * Check if current page is a tribute page
     *
     * @return boolean
     */
    function fcrm_plausible_is_tribute_page() {
        $is_tribute = isset($_GET['id']) && isset($_GET['tid']);
        return apply_filters( 'fcrm_plausible_is_tribute_page', $is_tribute );
    }

    /**
     * Load Plausible Analytics script on tribute pages
     *
     * @return void
     */
    function fcrm_plausible_load_on_tribute_pages() {
        // Check if we are on a tribute page
        if ( fcrm_plausible_is_tribute_page() ) {
            // Get the Plausible Analytics script URL
            $script_url = Plausible\Analytics\WP\Helpers::get_js_url( true );
            
            // Get the version
            $version = Plausible\Analytics\WP\Helpers::proxy_enabled() && file_exists( Plausible\Analytics\WP\Helpers::get_js_path() ) 
                ? filemtime( Plausible\Analytics\WP\Helpers::get_js_path() ) 
                : PLAUSIBLE_ANALYTICS_VERSION;
            
            // Enqueue the Plausible Analytics script
            wp_enqueue_script( 
                'plausible-analytics', 
                $script_url, 
                [], 
                $version, 
                apply_filters( 'plausible_load_js_in_footer', false ) 
            );

            // Add the inline script for goal tracking (optional)
            wp_add_inline_script(
                'plausible-analytics',
                'window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }'
            );
        }
    }
    add_action( 'wp_enqueue_scripts', 'fcrm_plausible_load_on_tribute_pages' );

} else {
    /**
     * Display admin notice if required plugins are not active
     */
    function fcrm_plausible_admin_notice() {
        $message = '<div class="error"><p><strong>FireHawkCRM Tributes - Plausible Analytics Integration:</strong> ';
        
        if ( ! in_array( 'fcrm-tributes/fcrm-tributes.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
            $message .= 'The FireHawkCRM Tributes plugin is not active. ';
        }
        
        if ( ! in_array( 'plausible-analytics/plausible-analytics.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
            $message .= 'The Plausible Analytics plugin is not active. ';
        }
        
        $message .= 'Please activate the required plugins to use this integration.</p></div>';
        echo $message;
    }
    add_action( 'admin_notices', 'fcrm_plausible_admin_notice' );
}